project:
  type: website
  output-dir: docs
  pre-render: generate-gallery.ts

website:
  title: "Growth Festival"
  favicon: assets/favicon.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: welcome.qmd
        text: Welcome
      - schedule.qmd
      - artists.qmd
      - text: Photo Galleries
        href: galleries.qmd

format:
  html:
    theme:
      - superhero
    css: styles.css
    toc: true
