---
title: "Growth 2025"
---

## Where?

Sasha's place 🏠

## When?

August 22nd - 24th. Check out the [full schedule](schedule.qmd).

## Why?

Read all about it [here](mission.qmd).

## Tickets

This is an invite only event, tickets are not required. That said, a whole lot
of time 📆, energy 🔋, and money 💸 has gone into making Growth happen and [**donations
keep this event alive**]{style="text-decoration: underline;"}. Cash donations can be made at the festival,
and email money transfers can be sent to [donations@growthfestival.ca](mailto:donations@growthfestival.ca).

Suggested donation is $50 for the weekend (or think of it as $25 / night).

::: {style="text-align: center"}
### Current total costs are approx. $4,000.00
:::

To see where the money goes, all [our expenses have been made public](https://docs.google.com/spreadsheets/d/e/2PACX-1vSdYrmyhNATk5joTprdlClZBsyZWNICSrKLt1Ka2CIpBk5UwdqkUTZNiijrvRGv6EEVTJCjxEhmoZLc/pubhtml).

## What To Do

* Arrive **no earlier than 2pm** on Friday Aug 22nd.
* Check in at the front gate.
* Unload your gear then **move your car**. To avoid unwanted attention please do not park on the street. The lot at the nearby Michael's (University & Erb) is large and usually empty. 


## What To Bring

* Yoga mat
* Plates, cups, and cutlery to help reduce trash at meal times.
* Camping gear if you plan to stay Friday / Saturday evening.

## Photos

If you have photos of Growth 2024 or take photos this year and would like to share them, please send them to [photos@growthfestival.ca](mailto:photos@growthfestival.ca).
