---
title: "Schedule"
---

## Friday Aug 22nd

Guests are asked to arrive no earlier than 2pm to allow us ample setup time.

Our resident grill master will BBQ dinner and we will host an eclectic mix of live musical performances in the forest behind our garden.

### Meals

> Note: all meals will be served at The Wandering Wizard Tavern & Eatery

* 6:00pm Dinner with Yazzi

### Main Stage

* 5:00pm Red Delicious
* 5:30pm Aptosis
* 6:00pm [Keecheekat](bios/keechakat.qmd)
* 6:30pm [Justine](bios/justine.qmd)
* 7:00pm [Feral Agathist](bios/feral-agathist.qmd)
* 7:30pm [Mistress Jen](bios/mistress-jen.qmd)
* 8:00pm [Diana & Mike Erb](bios/diana-and-mike.qmd)
* 8:30pm [Joanne Bender](bios/joanne-bender.qmd)
* 9:00pm [Alex Machidon](bios/alex-machidon.qmd)
* 9:30pm [mosspossom](bios/mosspossum.qmd)
* 10:00pm [Onion Honey](bios/onion-honey.qmd)

## Saturday Aug 23rd

Lazy brunch, as well as guided meditation and yoga sessions in the forest. Enjoy lounging in a hammock, plounging in the bell tent, playing board games or badminton, or getting down to some daytime DJ sets. You can also expect an intentional drum circle, a spoken word session featuring poetry and prose from some of our community's prolific wordsmiths, and a plethora of other surprises.

Dinner will be served by one of Waterloo Region's finest private chefs. Then it's time to get down on the dance floor with DJs playing from early evening until after dark.

### Meals

* 9am Brunch with [Keira](bios/keira.qmd)
* 6pm Dinner with [Terry Salmond](bios/terry-salmond.qmd)

### Activities

#### Kids Tent

* All Day: Crafting
* 12pm-2pm: Glitter Tattoos
* 3pm-5:30pm: Face Painting

#### Main Stage

* 10am Yoga with [Nas](bios/nas.qmd): No Mat? No Problems!
* 11am [Mike Tudisco](bios/mike-tudisco.qmd): Sound Healing
* 12pm [Michael Masurkevitch](bios/michael-masurkevitch.qmd): Meditation

### Workshops

#### Pergola

* 1pm [Jacob](bios/jacob.qmd): Countering Fascism
* 2pm [James Brown](bios/james-brown.qmd): Radical Acceptance - A Super Power
* 3pm [Lenna titizian](bios/lenna-titizian.qmd): Healing Our Money Relationships for Social Change
* 4pm [Andi Kujtan](bios/andi-kujtan.qmd): Meeting and Cultivating a Relationship With Your Inner Child

#### Garden

* 1-3pm [Ciara](bios/ciara.qmd): Reiki Sessions
* 4-5pm [Mike McPherson](bios/mike-mcpherson.qmd): What I Learned From 10 Years of Composting

#### Plounge

* 1-3pm [Sylvia Chapman](bios/sylvia-chapman.qmd): Crochet 101
* 4-5pm [Rob Salmond](bios/rob-salmond.qmd): Being Human for Human Beings

#### Wandering Wizard Tavern & Eatery

* 2-3pm [Jace J](bios/jace-j.qmd): From Beans to Brews - Exploring the Third Wave of Coffee
* 4-5pm: [David Wellhauser](bios/david-wellhauser.qmd): Star Trek

#### Film Lounge

* 2:30-4pm [Stephanie Trotter](bios/stephanie-trotter.qmd): Learn to Drop Spindle
* 4-5pm [Elysha](bios/elysha.qmd): Radical Mending

#### Thyme Patch

* 2-3pm [Ali Engering](bios/ali-engering.qmd): Nature Mindfulness - A Small Taste of Forest Bathing
* 3-4pm [Michael](bios/michael.qmd): Song Circle
* 4-5pm [Ali Engering](bios/ali-engering.qmd): Learn To Slackline -  Zero Experience Required!

#### Main Stage

* 2-3pm [Trash Theater](bios/trash-theatre.qmd): Loop There It Is

### Performances

#### Main Fire

* 5:30pm [JP](bios/jp.qmd): Magic Show
* 6pm Spoken Word
  * [Jason Schattman](bios/jason-schattman.qmd)
  * [Jyoti Solanki-Davie](bios/jyoti-solanki-davie.qmd): A Forest Without Trees
  * [Mov](bios/mov.qmd)
  * [Tyson Remers](bios/tyson-remers.qmd)
  * [Ulysses Maurer](bios/ulysses-maurer.qmd): Human Generated Words About AI Generated Words


#### Main Stage

* 3:30pm [Zozo](bios/zoe.qmd)
* 4:15pm [EQ8](bios/eq8.qmd)
* 5:00pm Eddie
* 5:30pm [DJ Delfine](bios/delfine.qmd)
* 6:20pm [DJ Skinnydip](bios/skinnydip.qmd)
* 7:10pm The Technicolour Wizard
* 8:00pm [DJ Jace](bios/dj-jace.qmd)
* 9:00pm [Bossi Nova](bios/bossi-nova.qmd)
* 10:00pm [Kasia](bios/kasia.qmd)
* 11:00pm [DJ Witch Hazel & Leon CloudJuicy](bios/witch-hazel-and-leon-cloudjuicy.qmd)

## Sunday Aug 24th

### Meals

* 8:00am Brunch

### Main Stage

* 9am Yoga with [Jyoti Solanki-Davie](bios/jyoti-solanki-davie.qmd)
* 10am Tear Down
* 12pm Tearful Farewells
