# Welcome To Growth 2025!

Growth exists as a space for us to celebrate creatively together, and to share in the growth that comes from our
collective expression. It’s an opportunity to share our gifts, skills, and talents as we weave webs of transformation
and strive to bring forth a better world.

As organizers, we strive for Growth to be a micro example of the world we want to live in. Growth centers our
interdependence and celebrates the process of becoming that characterizes all our lives within the web of
community we are co-creating. It’s a participatory gathering in which every dance floor needs a dancer, every dish
needs washing, and everyone has something valuable to contribute. Volunteer sign-up sheets are available at the
front gate.

Growth works to be a radically inclusive space that is anti-racist, anti-fascist, and strives to be free of homophobia,
transphobia, xenophobia, and ableism. We center care, compassion, relationality, and accountability over
punishment in all our interactions and embrace abolitionist and harm reduction principles. Safety is co-created,
and we build a safer space through mutual responsibility. A harm reduction tent is on site and vibe patrol
volunteers are out all night Friday and noon Saturday until the early hours Sunday to keep the vibes high.
Growth is free of commodification: nothing is bought, sold, or traded during the event—everything is offered
freely in the spirit of mutual aid, abundance, and radical generosity. This includes donations that support event
costs and compensation for main stage performers.

Growth aims to be in reciprocal relationship with the land, not just on it. Being mindful of the hidden costs of
consumption directs the choices we make on and for the land.

Being in right relationship with the land also means acknowledging treaties and the sovereignty of Indigenous
Peoples. This event takes place on the traditional territory of the Anishinaabe, Haudenosaunee, and Chonnonton
peoples. This territory is governed by the Dish with One Spoon Wampum, the Haldimand Tract agreements, and
the Two Row Wampum. We acknowledge the enduring presence, knowledge, and philosophies of Indigenous
peoples. We know that acknowledgment is not enough and are striving to learn what reconciliation can look like as
part of this event.

Please honour the pack-in, pack-out ethos of Growth. Bring your empty bottles and cans home with you. Please
also bring a drinking vessel, cutlery, and a plate or bowl to enjoy the meals that will be on offer throughout the
weekend. As this has been an exceptionally dry summer, we ask that you are mindful of smoking. Designated
smoking areas will be on site. For the safety of everyone please only smoke in these areas.
We ask that you walk, bus, cab, carpool, or bike to Growth, and avoid parking on McDougall Rd between Erb Street
and Keatsway. This small inconvenience will make a huge difference to the neighbours who so kindly accept our
event in the neighbourhood. After 11pm is quiet time. Please be mindful of volume and avoid hanging out
near the road. There is a whole festival set up on the land to enjoy.

A cash donation of $25/day at the front gate is recommended. E-transfers to donations@growthfestival.ca are also
welcome.

Thank you for choosing to celebrate Growth with us. We have a whole weekend of incredible meals, musicians,
performances, workshops, DJs, art, and more lined up. We hope you enjoy your time weaving the web of
community with us as we all continue to grow together.

With love and gratitude,
The Growth Team
